[package]
name = "my-agent"
version = "0.1.0"
authors = ["Jeff <fei.code@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
async-openai = "0.23.4"
